name: Deploy to Glitch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Deploy to Glitch
        uses: kanadgupta/glitch-sync@main
        with:
          project-id: ${{ secrets.GLITCH_PROJECT_ID }}
          auth-token: ${{ secrets.GLITCH_AUTH_TOKEN }}
